# overrides for local development, not used in CI
version: '3'
services:
  playwright:
    build:
      context: playwright
      cache_from:
        - type=registry,ref="registry.lil.tools/harvardlil/perma-playwright:buildcache"
      cache_to:
        - type=registry,ref="registry.lil.tools/harvardlil/perma-playwright:buildcache,type=max"
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-playwright:3-875732c19262d12a3d702955d828dfb7
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - requirements.txt
  web:
    build:
      context: .
      dockerfile: perma_web/Dockerfile
      cache_from:
        - type=registry,ref="registry.lil.tools/harvardlil/perma-web:buildcache"
      cache_to:
        - type=registry,ref="registry.lil.tools/harvardlil/perma-web:buildcache,type=max"
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/perma-web:14-d25a53cc4eb3596c7101c439cb9c7407
        platforms:
          - linux/amd64
          - linux/arm64
      x-hash-paths:
        - perma_web/requirements.txt
        - perma_web/npm-shrinkwrap.json
        - perma_web/package.json
        - perma_web/perma-warcprox-ca.pem
        - perma_web/lil-archive-keyring.gpg
